### ISSUE TITLE
Provide "Team Project Set" for the ContextQuickie team provider 

### ISSUE THREAD

**Issue by oilid** [ContextQuickie/ContextQuickie#24]
Hey @ContextQuickie,

after using your great feature of issue #22 we are looking how to provide the new ContextQuickie team provider for all of our developers.
We found the "Team Project Set" option/function in eclipse which should fit to our requirements.

In Eclipse you can export a "team project set" with:
File -> Export... -> Team -> Team Project Set
After choosing the projects you can save the exported project set in a file "projectSet.psf" for example.
This file is a xml-file which describes the team provider informations but is only usable with the new team provider of ContextQuickie if you provide your informations.

An exported project set file could imported during an eclipse installation (Oomph) for each developer automatically. So no one needs to choose "Share Project" for each of our projects manually which saves a lot of time for us.

Unfortunately I dont know so much about these project sets but I found these useful links:
- http://www.eclipseonetips.com/2010/01/25/checkout-multiple-projects-automatically-into-your-eclipse-workspace/
- https://stackoverflow.com/questions/42554608/structure-of-eclipse-psf-file

Could you please provide these import and export mechanism for the corresponding team project sets of the new ContextQuickie team provider?

Best regards,
Oilid

**Comment by ContextQuickie** [comment]
Hi @oilid ,
as far as a saw I have to somehow overwrite getProjectSetCapability() in SvnRepositoryProviderType to tell eclipse how to export/import the projects. I'll have a further look at it.
BR
Roland

**Comment by oilid** [comment]
Okay, thanks Roland :)

**Comment by ContextQuickie** [comment]
Hi @oilid,
I created a first test version for importing/exporting projects. It should do the following:
 - When exporting, it adds project references to the psf file containing the following information separated by semicolons: 
   - The project name
   - Tthe repository URL of the root of the working copy
   - The root of the working copy
   - The project location in the working copy
 - When importing, it performs the following steps:
   - Check if the working copy directory exists. If not, the repository will be checked out **fully recursive**
  - Check if the project directory exists. If it exists, the plugin tries to create a project from the project directory and map it to the Team Provider.

Does this fit to your expectations? If yes: can you please have a look at it?

BR
Roland

**Comment by oilid** [comment]
Hey @ContextQuickie,

I started testing the project team sets and I had some problems:
- during the import process I got the following error:
```
The following errors occurred while importing projects. Some projects may not be loaded.
  Unable to create project foo-app
    Failed to read project description file from location 'C:\projects\foo-trunk2\work\foo-app-aggregator\foo-app\.project'.
    C:\projects\foo-trunk2\work\foo-app-aggregator\foo-app\.project (Das System kann die angegebene Datei nicht finden)
```
Our projects hasn't the ".project" in the svn repository. I think the problem is the project will not be imported to the workspace after the svn checkout.
- Another problem is the location of exported working copy. If you export a project you would import typically in the workspace of another eclipse installation. So I think the locations of the working copy in the "projectSet.psf" should be removed completly. The import should be done into the current using eclipse workspace with the specified project name (first value of your "reference").
So one project reference should only look like:
`<project reference="foo-app;https://svn.de/svn/foo/foo/trunk/foo-app-aggregator/foo-app"/>`

Could you please change/fix this?

Best regards,
Oilid

**Comment by ContextQuickie** [comment]
Hello @oilid,
I added support for workspace relative directories. They can be set by using ${WORKSPACE_LOC} in the export file. This keeps the possibility to import also projects which are located outside the workspace.
What I did not yet understand: If you don't have the .project file in your repository, how do you currently get your projects into eclipse? Do you always create new projects or is there a way to import projects without .project files?
BR
Roland

**Comment by oilid** [comment]
Hey @ContextQuickie,

I think you dont need the "${WORKSPACE_LOC}" in the team project set, because when I have a look at subclipse and their project set file:
```
<?xml version="1.0" encoding="UTF-8"?>
<psf version="2.0">
<provider id="org.tigris.subversion.subclipse.core.svnnature">
<project reference="0.9.3,https://svn.de/svn/foo/foo-common/trunk,foo-common"/>
<project reference="0.9.3,https://svn.de/svn/platform-libs/p2mirror/p2mirror-emf/trunk,p2mirror-emf"/>
<project reference="0.9.3,https://svn.de/svn/platform-libs/p2mirror/p2mirror-oomph/trunk,p2mirror-oomph"/>
<project reference="0.9.3,https://svn.de/svn/platform-libs/p2mirror/p2mirror-xtext/trunk,p2mirror-xtext"/>
</provider>
</psf>
```
I think 0.9.3 is just a version number of the plugin.
We import the projects by a Oomph setup task as maven projects. In the UI there is also a possibility to import maven projects. So there is no need for a ".project" file because of the pom.xml.
BUT I think the best would be to have a look at the subclipse plugin code (https://github.com/subclipse/subclipse) how they handle the export and import. I think your code should be nearly the same ;-)

Greetings,
Oilid

**Comment by ContextQuickie** [comment]
Hi @oilid ,
I want to keep the option to set the checkout directory and the project directory because I use SVN in this way. But to reduce the data, I implemented the following:
- If the project to export is in the workspace, I only save the project name and the SVN repo URL and import it to the workspace again.
- In all other cases I add the project path and the checkout path to the PSF file.

I don't want to copy code from subclipse because then I have to deal with additional licenses. I'll check how projects can be imported without having a .project file. Do you know if this is working with subclipse?
BR
Roland

**Comment by oilid** [comment]
Hey @ContextQuickie,

yes, it works without ".project" file in subclipse. The project will be successfully imported with the team project set file as eclipse project.

Greetings
Oilid

**Comment by oilid** [comment]
Hey @ContextQuickie,

is the issue still in progress?

Regards,
Oilid

**Comment by ContextQuickie** [comment]
Hello @oilid ,
yes, but currently I don't have any time to continue.
Hopefully in the next weeks.
Roland

**Comment by ContextQuickie** [comment]
Hello @oilid,
sorry for the long delay. Now I had time to have a look at this issue again. I added a new version to the development update site which also can import projects without .project file.
It works generally but the project nature (which is stored in the .project file) is missing after the import and has to be set manually in the project settings after importing. Do you know if subclipse works in the same way?
BR
Roland

**Comment by oilid** [comment]
Hey @ContextQuickie ,

thanks a lot! I just checked the new dev version.
After exporting the team project set, I manually removed the last value of the project reference (with the project location).
Then I imported the project set file into eclipse and the ".project" file will be created automatically. So thats not the problem. But in our case the projects are maven projects. So I converted the project into a maven project manually. But than I got the following problem:
```
ContextQuickie.TeamProvider
Error during applying changes to working copy
Eintrag existiert bereits
svn: Pfad »C:\Users\blubb\eclipse-workspace\taglib\bin\src\main\java\de\foo\bmanwfam\taglib2\images\textarea.gif« existiert bereits
```
I think the "bin" output folder is the problem here because before converting to maven the bin folder was the java output folder and after converting to maven the target folder is the java output folder of the project.

But I will ask my colleague tomorrow if this is really a problem when we import our projects by your team project set. So I will write you again.

Best Regards,
Oilid

**Comment by oilid** [comment]
Hey @ContextQuickie,

we just tested the dev-version and had a problem:
Imagine the following team project file:
```
<?xml version="1.0" encoding="UTF-8"?>
<psf version="2.0">
<provider id="contextquickie.teamprovider.svn.SvnRepositoryProvider">
<project reference="test-project;https://svn.test.de/svn/test-project;C:/temp/test-project"/>
</provider>
</psf>
```
In this case the eclipse project (with the .project file) will be created in the default eclipse-workspace location for example under "C:\Users\oilid\eclipse-workspace\test-project" but the the svn sources will be checked out under "C:/temp/test-project" (as shown in the psf-file above). So these both locations doesn't match / are not the same. But I expected that the "test-project" is completly located under "C:/temp/test-project" as defined above.

Just as background why we want to use your location definition in the psf-file: We have a maven multi module project. And if we would checkout/import only the root maven project with the team project set the ContextQuickie provider will **not** be configured for each child-projects (but only for this root project). This is the root cause. So we had the idea to add each child-project (and the root project itself) into the team project set file.
This would work for us because it seems that you luckily don't checkout / overwrite a project again if it is already located in the checkout folder (the last parameter above of your seperated list).

Just as explanation, this is our (maven) project structure in svn:
```
test-app-aggregator
   |_ test-app
   |_ test-model
   |_ test-web
   ...
```
So could you fix the checkout / workspace location problem as described above?

Best regards
Oilid

**Comment by ContextQuickie** [comment]
Hello @oilid,
the fixed version is available at the update site now.
BR
Roland

**Comment by oilid** [comment]
Hey @ContextQuickie,

yes thats it. It works as expected. Thanks a lot.
Can you release it now?

Best Regards,
Oilid

**Comment by ContextQuickie** [comment]
Hi @oilid ,
the new version is now available on the release update site.
You can close this issue if there aren't any further topics from your side.
BR
Roland
